/** Autogenerated from YouTube Data API v3 (2026-09-08). Do not edit by hand. */
window.LATEST_VIDEOS = [
  {
    "id": "CLjUCxyEXuY",
    "title": "This Ship Sailed Fine — All 10 People Had Vanished",
    "thumb": "https://i.ytimg.com/vi/CLjUCxyEXuY/mqdefault.jpg",
    "views": 358,
    "likes": 10,
    "duration": 141,
    "published": "2026-09-08T09:36:09Z"
  },
  {
    "id": "4Qk1GZS9YdU",
    "title": "The Door Is Still Open — Titanic Ep.1 Ending (AI Historical Short)",
    "thumb": "https://i.ytimg.com/vi/4Qk1GZS9YdU/mqdefault.jpg",
    "views": 251,
    "likes": 2,
    "duration": 44,
    "published": "2026-08-30T01:25:47Z"
  },
  {
    "id": "a5ZcZJHC-lQ",
    "title": "11:40 PM On The Titanic — The Sinking Begins (AI Historical Short)",
    "thumb": "https://i.ytimg.com/vi/a5ZcZJHC-lQ/mqdefault.jpg",
    "views": 174,
    "likes": 2,
    "duration": 39,
    "published": "2026-08-30T01:25:46Z"
  },
  {
    "id": "XEJq6Ersk_4",
    "title": "POV: You Wake Up On The Titanic — The Hook (AI Historical Short)",
    "thumb": "https://i.ytimg.com/vi/XEJq6Ersk_4/mqdefault.jpg",
    "views": 125,
    "likes": 1,
    "duration": 29,
    "published": "2026-08-30T01:25:29Z"
  },
  {
    "id": "d4MIzWTf99A",
    "title": "POV: You Wake Up On The Titanic — April 14, 1912 | AI Historical Documentary",
    "thumb": "https://i.ytimg.com/vi/d4MIzWTf99A/mqdefault.jpg",
    "views": 18,
    "likes": 1,
    "duration": 193,
    "published": "2026-08-30T01:23:12Z"
  },
  {
    "id": "iAp6u-50q3s",
    "title": "NIGHT SHIFT AT REACTOR 4 — Chernobyl, April 25 1986 (Historical POV)",
    "thumb": "https://i.ytimg.com/vi/iAp6u-50q3s/mqdefault.jpg",
    "views": 16,
    "likes": 2,
    "duration": 233,
    "published": "2026-08-28T16:00:32Z"
  },
  {
    "id": "0m9sP3wAxGw",
    "title": "Menes: Unifier of the Two Lands — Ch.5: The Unified Crown #egypt #anime #pharaonic",
    "thumb": "https://i.ytimg.com/vi/0m9sP3wAxGw/mqdefault.jpg",
    "views": 257,
    "likes": 9,
    "duration": 36,
    "published": "2026-08-27T16:00:39Z"
  },
  {
    "id": "uLKqjNR8KMc",
    "title": "The Night Chernobyl Killed Itself — POV",
    "thumb": "https://i.ytimg.com/vi/uLKqjNR8KMc/mqdefault.jpg",
    "views": 108,
    "likes": 4,
    "duration": 30,
    "published": "2026-08-26T21:11:48Z"
  },
  {
    "id": "EBdsozeCMXs",
    "title": "حين وُلد النيل — بداية الحضارة 🏺 | EP1",
    "thumb": "https://i.ytimg.com/vi/EBdsozeCMXs/mqdefault.jpg",
    "views": 17,
    "likes": 3,
    "duration": 753,
    "published": "2026-08-26T16:00:06Z"
  },
  {
    "id": "UqCFF9cqYtQ",
    "title": "Menes: Unifier of the Two Lands — Ch.4: The Decisive Battle #egypt #anime #pharaonic",
    "thumb": "https://i.ytimg.com/vi/UqCFF9cqYtQ/mqdefault.jpg",
    "views": 39,
    "likes": 3,
    "duration": 79,
    "published": "2026-08-26T16:00:06Z"
  },
  {
    "id": "5nK-F3Frp_s",
    "title": "The Lost Architecture of Thoth — Revealed Through Stunning Neon Anime 🟢👁️",
    "thumb": "https://i.ytimg.com/vi/5nK-F3Frp_s/mqdefault.jpg",
    "views": 10,
    "likes": 2,
    "duration": 132,
    "published": "2026-08-25T16:42:27Z"
  },
  {
    "id": "in7YaY5m_D4",
    "title": "Thoth's blueprints are VANISHING... 🟢👁️ #shorts",
    "thumb": "https://i.ytimg.com/vi/in7YaY5m_D4/mqdefault.jpg",
    "views": 27,
    "likes": 2,
    "duration": 24,
    "published": "2026-08-25T16:40:53Z"
  }
];
